name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - k8s-manifest/**
      - README.md
      - terraform/**
  pull_request:
    branches: [main]

jobs:
  sast_scan:
    name: SAST scan 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
     
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r app/ -f json -o bandit-report.json || true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sast_scan  # Ensure SAST scan runs first

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest ./app

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

