name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - k8s-manifest/**
      - README.md
  pull_request:
    branches: [main]

jobs:
  sast_scan:
    name: SAST scan 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
     
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r app/ -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json